"use client";

import { createContext, useContext, useState, type CSSProperties, type ReactNode } from "react";
import * as Select from "@radix-ui/react-select";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Check, ChevronDown, Moon, Search, Sun } from "lucide-react";

interface TableTheme {
  dark: boolean;
  surface: string;
  surfaceMuted: string;
  surfaceRaised: string;
  border: string;
  text: string;
  muted: string;
  subtle: string;
  accent: string;
}

const ThemeContext = createContext<TableTheme | null>(null);

export function useTableTheme() {
  const theme = useContext(ThemeContext);
  if (!theme) throw new Error("useTableTheme must be used inside TableShell");
  return theme;
}

export function TableShell({ children, darkDefault = false }: { children: ReactNode; darkDefault?: boolean }) {
  const [dark, setDark] = useState(darkDefault);
  const theme: TableTheme = dark
    ? { dark, surface: "#0b0d12", surfaceMuted: "#11141b", surfaceRaised: "#171b24", border: "#252b36", text: "#f8fafc", muted: "#a7b0c0", subtle: "#6f7a8c", accent: "#6366f1" }
    : { dark, surface: "#ffffff", surfaceMuted: "#f7f8fb", surfaceRaised: "#ffffff", border: "#e3e7ee", text: "#111827", muted: "#526071", subtle: "#8a95a5", accent: "#4f46e5" };
  const vars = { "--tbl-bg": theme.surface, "--tbl-muted-bg": theme.surfaceMuted, "--tbl-raised": theme.surfaceRaised, "--tbl-border": theme.border, "--tbl-text": theme.text, "--tbl-muted": theme.muted, "--tbl-subtle": theme.subtle, "--tbl-accent": theme.accent } as CSSProperties;
  return (
    <ThemeContext.Provider value={theme}>
      <div data-table-theme={dark ? "dark" : "light"} className={dark ? "table-demo dark" : "table-demo"} style={vars}>
        <style>{TABLE_STYLES}</style>
        {children}
        <button type="button" className="table-theme-toggle" onClick={() => setDark((value) => !value)} aria-label={dark ? "Use light table theme" : "Use dark table theme"} aria-pressed={dark}>
          {dark ? <Sun aria-hidden="true" /> : <Moon aria-hidden="true" />}
        </button>
      </div>
    </ThemeContext.Provider>
  );
}

export function TableHeader({ title, description, children }: { title: string; description: string; children?: ReactNode }) {
  return <header className="table-header"><div className="table-heading"><h1>{title}</h1><p>{description}</p></div><div className="table-actions">{children}</div></header>;
}

export function TableSearch({ value, onChange, placeholder = "Search records" }: { value: string; onChange: (value: string) => void; placeholder?: string }) {
  return <label className="table-search"><span className="sr-only">{placeholder}</span><Search aria-hidden="true" /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;
}

export interface TableSelectOption { value: string; label: string }
export function TableSelect({ value, onChange, options, label, compact = false }: { value: string; onChange: (value: string) => void; options: TableSelectOption[]; label: string; compact?: boolean }) {
  const theme = useTableTheme();
  const portalVars = { "--tbl-bg": theme.surface, "--tbl-muted-bg": theme.surfaceMuted, "--tbl-raised": theme.surfaceRaised, "--tbl-border": theme.border, "--tbl-text": theme.text, "--tbl-muted": theme.muted, "--tbl-subtle": theme.subtle, "--tbl-accent": theme.accent } as CSSProperties;
  return <Select.Root value={value} onValueChange={onChange}><Select.Trigger className={`table-select-trigger ${compact ? "table-select-compact" : ""}`} aria-label={label}><Select.Value /><Select.Icon><ChevronDown aria-hidden="true" /></Select.Icon></Select.Trigger><Select.Portal><Select.Content className="table-select-content" style={portalVars} position="popper" sideOffset={6} collisionPadding={12}><Select.Viewport className="table-select-viewport">{options.map((option) => <Select.Item className="table-select-item" key={option.value} value={option.value}><Select.ItemText>{option.label}</Select.ItemText><Select.ItemIndicator><Check aria-hidden="true" /></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root>;
}

export interface TableChecklistOption { value: string; label: string }
export function TableChecklist({ label, options, selected, onToggle, disabled }: { label: ReactNode; options: TableChecklistOption[]; selected: Set<string>; onToggle: (value: string) => void; disabled?: (value: string) => boolean }) {
  const theme = useTableTheme();
  const portalVars = { "--tbl-bg": theme.surface, "--tbl-muted-bg": theme.surfaceMuted, "--tbl-raised": theme.surfaceRaised, "--tbl-border": theme.border, "--tbl-text": theme.text, "--tbl-muted": theme.muted, "--tbl-subtle": theme.subtle, "--tbl-accent": theme.accent } as CSSProperties;
  return <DropdownMenu.Root><DropdownMenu.Trigger className="table-button">{label}<ChevronDown aria-hidden="true" /></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="table-dropdown-content" style={portalVars} sideOffset={6} collisionPadding={12} align="end">{options.map((option) => <DropdownMenu.CheckboxItem className="table-dropdown-item" key={option.value} checked={selected.has(option.value)} disabled={disabled?.(option.value)} onSelect={(event) => event.preventDefault()} onCheckedChange={() => onToggle(option.value)}><span className="table-dropdown-check"><DropdownMenu.ItemIndicator><Check aria-hidden="true" /></DropdownMenu.ItemIndicator></span>{option.label}</DropdownMenu.CheckboxItem>)}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>;
}

export function Initials({ name }: { name: string }) {
  const label = name.split(" ").map((part) => part[0]).join("").slice(0, 2);
  return <span className="table-avatar" aria-hidden="true">{label}</span>;
}

export function StatusBadge({ status }: { status: string }) {
  return <span className={`table-badge table-badge-${status.toLowerCase().replaceAll(" ", "-")}`}><span aria-hidden="true" />{status}</span>;
}
const TABLE_STYLES = `
.table-demo{container-type:inline-size;position:relative;display:flex;height:100%;min-height:440px;width:100%;flex-direction:column;overflow:hidden;background:var(--tbl-bg);color:var(--tbl-text);font-family:var(--font-sans),ui-sans-serif,system-ui}
.table-demo *{box-sizing:border-box}.table-header{display:flex;min-height:76px;flex:none;align-items:center;gap:20px;border-bottom:1px solid var(--tbl-border);padding:14px 64px 14px 20px;background:color-mix(in srgb,var(--tbl-bg) 92%,transparent)}
.table-heading{min-width:150px}.table-heading h1{font-size:15px;font-weight:750;letter-spacing:-.02em}.table-heading p{margin-top:2px;color:var(--tbl-subtle);font-size:11px}.table-actions{margin-left:auto;display:flex;min-width:0;align-items:center;justify-content:flex-end;gap:8px}
.table-theme-toggle,.table-icon-button{display:inline-flex;height:34px;width:34px;flex:none;align-items:center;justify-content:center;border:1px solid var(--tbl-border);border-radius:10px;background:var(--tbl-raised);color:var(--tbl-muted);transition:border-color .16s ease,color .16s ease,transform .16s ease}.table-theme-toggle{position:absolute;right:16px;top:20px;z-index:40}.table-theme-toggle svg,.table-icon-button svg{height:15px;width:15px}.table-theme-toggle:hover,.table-icon-button:hover{border-color:color-mix(in srgb,var(--tbl-accent) 55%,var(--tbl-border));color:var(--tbl-accent)}
.table-search{position:relative;display:flex;min-width:180px}.table-search svg{pointer-events:none;position:absolute;left:11px;top:50%;height:14px;width:14px;transform:translateY(-50%);color:var(--tbl-subtle)}.table-search input,.table-control{height:34px;border:1px solid var(--tbl-border);border-radius:10px;background:var(--tbl-muted-bg);color:var(--tbl-text);font-size:12px;outline:none}.table-search input{width:100%;padding:0 12px 0 34px}.table-search input:focus{border-color:var(--tbl-border);box-shadow:none}.table-control:focus{border-color:var(--tbl-accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--tbl-accent) 14%,transparent)}
.table-button{display:inline-flex;height:34px;align-items:center;justify-content:center;gap:7px;border:1px solid var(--tbl-border);border-radius:10px;padding:0 11px;background:var(--tbl-raised);color:var(--tbl-muted);font-size:11px;font-weight:650;white-space:nowrap;transition:.16s ease}.table-button svg{height:14px;width:14px}.table-button:hover{border-color:color-mix(in srgb,var(--tbl-accent) 45%,var(--tbl-border));color:var(--tbl-text)}.table-button-primary{border-color:var(--tbl-accent);background:var(--tbl-accent);color:white}.table-button-primary:hover{color:white;filter:brightness(1.06)}.table-button[aria-pressed=true]{border-color:var(--tbl-accent);background:color-mix(in srgb,var(--tbl-accent) 12%,var(--tbl-bg));color:var(--tbl-accent)}
.table-scroll{min-height:0;flex:1;overflow:auto;scrollbar-width:thin}.table-native{width:100%;min-width:760px;border-collapse:separate;border-spacing:0;font-size:12px}.table-native caption{position:absolute;height:1px;width:1px;overflow:hidden;clip:rect(0 0 0 0)}.table-native th{position:sticky;top:0;z-index:5;height:40px;border-bottom:1px solid var(--tbl-border);background:var(--tbl-muted-bg);padding:0 14px;color:var(--tbl-subtle);font-size:9px;font-weight:750;letter-spacing:.1em;text-align:left;text-transform:uppercase;white-space:nowrap}.table-native td{height:50px;border-bottom:1px solid var(--tbl-border);padding:8px 14px;color:var(--tbl-muted);white-space:nowrap}.table-native tbody tr{background:var(--tbl-bg);transition:background .14s ease}.table-native tbody tr:hover{background:var(--tbl-muted-bg)}.table-native .table-compact-row td{height:38px;padding-top:5px;padding-bottom:5px}.table-native .table-striped-row:nth-child(even){background:var(--tbl-muted-bg)}
.table-sort{display:inline-flex;align-items:center;gap:5px;color:inherit}.table-sort svg{height:11px;width:11px}.table-primary{font-weight:680;color:var(--tbl-text)}.table-secondary{color:var(--tbl-subtle)}.table-mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.table-number{font-variant-numeric:tabular-nums}.table-person{display:flex;align-items:center;gap:9px}.table-avatar{display:inline-flex;height:28px;width:28px;flex:none;align-items:center;justify-content:center;border:1px solid color-mix(in srgb,var(--tbl-accent) 22%,var(--tbl-border));border-radius:9px;background:color-mix(in srgb,var(--tbl-accent) 9%,var(--tbl-bg));color:var(--tbl-accent);font-size:9px;font-weight:800}.table-person-copy{min-width:0}.table-person-copy>*{overflow:hidden;text-overflow:ellipsis}.table-badge{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:4px 8px;background:var(--tbl-muted-bg);color:var(--tbl-muted);font-size:10px;font-weight:700;text-transform:capitalize}.table-badge>span{height:6px;width:6px;border-radius:50%;background:currentColor}.table-badge-active,.table-badge-paid,.table-badge-delivered,.table-badge-success,.table-badge-low{background:rgba(16,185,129,.1);color:#10b981}.table-badge-invited,.table-badge-pending,.table-badge-processing,.table-badge-warning,.table-badge-medium{background:rgba(245,158,11,.11);color:#d97706}.dark .table-badge-invited,.dark .table-badge-pending,.dark .table-badge-processing,.dark .table-badge-warning,.dark .table-badge-medium{color:#fbbf24}.table-badge-suspended,.table-badge-refunded,.table-badge-review,.table-badge-high{background:rgba(244,63,94,.1);color:#e11d48}.dark .table-badge-suspended,.dark .table-badge-refunded,.dark .table-badge-review,.dark .table-badge-high{color:#fb7185}.table-badge-shipped,.table-badge-info{background:rgba(59,130,246,.1);color:#3b82f6}
.table-checkbox{height:16px;width:16px;accent-color:var(--tbl-accent)}.table-empty{display:flex;min-height:240px;flex-direction:column;align-items:center;justify-content:center;color:var(--tbl-subtle);font-size:12px}.table-footer{display:flex;min-height:48px;flex:none;align-items:center;gap:12px;border-top:1px solid var(--tbl-border);padding:8px 64px 8px 16px;color:var(--tbl-subtle);font-size:11px}.table-pager{margin-left:auto;display:flex;gap:5px}.table-pager button{height:29px;min-width:29px;border:1px solid var(--tbl-border);border-radius:8px;background:var(--tbl-raised);color:var(--tbl-muted)}.table-pager button:disabled{opacity:.35}.table-pager button[aria-current=page]{border-color:var(--tbl-accent);background:var(--tbl-accent);color:#fff}
.table-toolbar{display:flex;align-items:center;gap:7px;border-bottom:1px solid var(--tbl-border);padding:9px 64px 9px 16px;background:var(--tbl-muted-bg)}.table-summary{font-size:11px;color:var(--tbl-subtle)}.table-summary strong{color:var(--tbl-text)}.table-spacer{flex:1}.table-menu{position:relative}.table-menu-panel{position:absolute;right:0;top:calc(100% + 6px);z-index:30;min-width:190px;border:1px solid var(--tbl-border);border-radius:12px;padding:6px;background:var(--tbl-raised);box-shadow:0 18px 50px rgba(15,23,42,.16)}.table-menu-panel label{display:flex;cursor:pointer;align-items:center;gap:9px;border-radius:8px;padding:7px;color:var(--tbl-muted);font-size:11px}.table-menu-panel label:hover{background:var(--tbl-muted-bg)}
.table-card-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:14px}.table-record-card{border:1px solid var(--tbl-border);border-radius:14px;padding:14px;background:var(--tbl-raised);box-shadow:0 8px 24px rgba(15,23,42,.04)}.table-record-card dl{margin-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.table-record-card dt{color:var(--tbl-subtle);font-size:9px;font-weight:700;text-transform:uppercase}.table-record-card dd{margin-top:2px;color:var(--tbl-text);font-size:11px;font-weight:650}
.table-edit-input{height:30px;width:100%;min-width:110px;border:1px solid var(--tbl-accent);border-radius:7px;padding:0 8px;background:var(--tbl-raised);color:var(--tbl-text);font-size:11px;outline:none}.table-row-actions{display:flex;gap:5px}.table-row-actions button{display:inline-flex;height:27px;width:27px;align-items:center;justify-content:center;border:1px solid var(--tbl-border);border-radius:8px;color:var(--tbl-muted)}.table-row-actions svg{height:13px;width:13px}.table-detail{padding:16px 18px;background:var(--tbl-muted-bg)}.table-detail-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.table-detail-grid dt{color:var(--tbl-subtle);font-size:9px;font-weight:750;text-transform:uppercase}.table-detail-grid dd{margin-top:4px;color:var(--tbl-text);font-size:12px;font-weight:600}
.table-sticky-first{position:sticky;left:0;z-index:4!important;background:inherit!important;box-shadow:8px 0 16px -16px #000}.table-spark{height:24px;width:76px}.table-tree-toggle{display:inline-flex;height:26px;width:26px;align-items:center;justify-content:center;border-radius:7px;color:var(--tbl-subtle)}.table-tree-toggle:hover{background:var(--tbl-raised);color:var(--tbl-accent)}.table-tree-toggle svg{height:14px;width:14px;transition:transform .16s}.table-tree-toggle[aria-expanded=true] svg{transform:rotate(90deg)}
.table-virtual-head,.table-virtual-row{display:grid;min-width:760px;grid-template-columns:110px minmax(190px,1.4fr) minmax(150px,1fr) minmax(130px,1fr) 110px 100px;align-items:center}.table-virtual-head{height:40px;border-bottom:1px solid var(--tbl-border);background:var(--tbl-muted-bg);color:var(--tbl-subtle);font-size:9px;font-weight:750;letter-spacing:.1em;text-transform:uppercase}.table-virtual-head>*{padding:0 14px}.table-virtual-row{position:absolute;left:0;top:0;width:100%;border-bottom:1px solid var(--tbl-border);font-size:11px}.table-virtual-row>*{overflow:hidden;padding:0 14px;text-overflow:ellipsis;white-space:nowrap}.table-virtual-row:hover{background:var(--tbl-muted-bg)}
.table-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;border-bottom:1px solid var(--tbl-border);background:var(--tbl-border)}.table-kpi{padding:11px 16px;background:var(--tbl-bg)}.table-kpi span{color:var(--tbl-subtle);font-size:9px;font-weight:700;text-transform:uppercase}.table-kpi strong{display:block;margin-top:2px;color:var(--tbl-text);font-size:15px}.table-filter-row{display:flex;flex-wrap:wrap;gap:6px;border-bottom:1px solid var(--tbl-border);padding:8px 64px 8px 16px;background:var(--tbl-muted-bg)}.table-filter-row .table-control{padding:0 9px}.table-density-compact .table-native td{height:38px;padding-top:5px;padding-bottom:5px}.table-density-comfortable .table-native td{height:58px}
.table-mobile-only{display:none}.table-desktop-only{display:block}
.table-demo button:focus-visible{outline:2px solid color-mix(in srgb,var(--tbl-accent) 60%,transparent);outline-offset:2px}.table-demo .table-search input:focus-visible{outline:none}.table-demo .table-select-trigger:focus-visible{outline:none}
@container (max-width:760px){.table-header{min-height:auto;align-items:flex-start;flex-direction:column;padding:14px 58px 12px 14px}.table-heading p{max-width:38ch}.table-actions{margin-left:0;width:100%;justify-content:flex-start;flex-wrap:wrap}.table-search{min-width:min(100%,230px);flex:1}.table-toolbar,.table-filter-row{padding-right:58px;flex-wrap:wrap}.table-card-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.table-detail-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.table-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.table-footer{padding-right:58px}.table-responsive-auto .table-desktop-only{display:none}.table-responsive-auto .table-mobile-only{display:grid}.table-theme-toggle{right:12px;top:14px}}
@container (max-width:480px){.table-heading p{display:none}.table-button span{display:none}.table-card-grid{grid-template-columns:1fr;padding:10px}.table-detail-grid{grid-template-columns:1fr}.table-kpis{grid-template-columns:1fr 1fr}.table-footer{flex-wrap:wrap}.table-pager{margin-left:0}.table-hide-narrow{display:none}}
@media (prefers-reduced-motion:reduce){.table-demo *{scroll-behavior:auto!important;transition-duration:.001ms!important}}
/* Material-inspired production surface */
.table-demo{padding:14px;background:#f3f5f9}.table-demo.dark{background:#080b11}.table-demo>div{min-height:0;border:1px solid var(--tbl-border);border-radius:18px;overflow:hidden;background:var(--tbl-bg);box-shadow:0 1px 2px rgba(15,23,42,.04),0 12px 34px rgba(15,23,42,.07)}.table-demo.dark>div{box-shadow:0 18px 50px rgba(0,0,0,.28)}
.table-header{position:relative;z-index:15;min-height:86px;padding:17px 68px 17px 22px;background:var(--tbl-bg)}.table-heading h1{font-size:17px;font-weight:720;letter-spacing:-.025em}.table-heading p{max-width:48ch;margin-top:3px;line-height:1.45}.table-actions{gap:7px}.table-theme-toggle{right:28px;top:32px;border-radius:50%;box-shadow:0 3px 10px rgba(15,23,42,.08)}
.table-search input,.table-control,.table-select-trigger{height:38px;border-color:transparent;border-radius:9px;background:var(--tbl-muted-bg)}.table-search input:hover,.table-control:hover,.table-select-trigger:hover{border-color:var(--tbl-border)}.table-search input:focus{background:var(--tbl-raised)}.table-button,.table-icon-button{height:38px;border-radius:9px;box-shadow:0 1px 1px rgba(15,23,42,.03)}.table-button-primary{box-shadow:0 5px 13px color-mix(in srgb,var(--tbl-accent) 24%,transparent)}
.table-select-trigger{display:inline-flex;min-width:132px;align-items:center;justify-content:space-between;gap:10px;border:1px solid transparent;padding:0 10px;color:var(--tbl-text);font-size:11px;font-weight:600;outline:none}.table-select-trigger svg{height:14px;width:14px;color:var(--tbl-subtle)}.table-select-trigger[data-state=open]{border-color:var(--tbl-accent);background:var(--tbl-raised);box-shadow:0 0 0 3px color-mix(in srgb,var(--tbl-accent) 12%,transparent)}.table-select-compact{height:30px;min-width:112px}.table-select-content,.table-dropdown-content{z-index:9999;max-height:min(280px,var(--radix-select-content-available-height,280px));overflow:hidden;border:1px solid var(--tbl-border);border-radius:12px;padding:5px;background:var(--tbl-raised);color:var(--tbl-text);box-shadow:0 18px 55px rgba(15,23,42,.18);animation:table-pop .14s cubic-bezier(.2,.8,.2,1)}.table-select-viewport{max-height:260px;overflow-y:auto;padding:1px;scrollbar-width:thin}.table-select-item,.table-dropdown-item{position:relative;display:flex;min-width:170px;cursor:default;user-select:none;align-items:center;justify-content:space-between;gap:12px;border-radius:8px;padding:8px 9px;color:var(--tbl-muted);font-size:11px;font-weight:580;outline:none}.table-select-item svg,.table-dropdown-item svg{height:13px;width:13px}.table-select-item[data-highlighted],.table-dropdown-item[data-highlighted]{background:color-mix(in srgb,var(--tbl-accent) 9%,var(--tbl-bg));color:var(--tbl-accent)}.table-select-item[data-state=checked]{color:var(--tbl-accent)}.table-dropdown-item[data-disabled]{opacity:.4}.table-dropdown-check{display:inline-flex;height:17px;width:17px;align-items:center;justify-content:center;border:1px solid var(--tbl-border);border-radius:5px}.table-dropdown-item[data-state=checked] .table-dropdown-check{border-color:var(--tbl-accent);background:var(--tbl-accent);color:#fff}@keyframes table-pop{from{opacity:0;transform:translateY(-3px) scale(.98)}to{opacity:1;transform:none}}
.table-toolbar,.table-filter-row{position:relative;z-index:10;min-height:48px;background:var(--tbl-muted-bg)}.table-scroll{overscroll-behavior:contain;scrollbar-gutter:stable}.table-native{min-width:820px}.table-native th{height:46px;background:var(--tbl-muted-bg);font-size:10px;letter-spacing:.07em}.table-native td{height:56px}.table-native tbody tr:last-child td{border-bottom:0}.table-native tbody tr:hover{background:color-mix(in srgb,var(--tbl-accent) 4%,var(--tbl-bg))}.table-checkbox{height:17px;width:17px}.table-avatar{height:32px;width:32px;border-radius:50%;font-size:10px}.table-badge{padding:5px 9px}.table-footer{min-height:54px;background:var(--tbl-bg)}.table-pager button{height:32px;min-width:32px;border-color:transparent;background:transparent}.table-pager button:hover:not(:disabled){background:var(--tbl-muted-bg)}.table-record-card{border-radius:16px;padding:16px;box-shadow:0 2px 9px rgba(15,23,42,.05)}.table-kpi{padding:14px 18px}.table-kpi strong{font-size:17px}.table-menu-panel{display:none}
@container (max-width:760px){.table-demo{padding:8px}.table-demo>div{border-radius:14px}.table-header{padding:14px 58px 13px 14px}.table-theme-toggle{right:20px;top:22px}.table-native{min-width:760px}}
`;
